### ISSUE TITLE
Account backup doesn't work on android

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#3176]
Hi, for me the acount backup button doesn't quite work. When choosing the google drive one it doesn't put any files in my google drive, and when mailing to myself I just sent an empty email to myself withou files.

If you need any information let me know.

**Comment by aeddi** [comment]
Hello,

This feature has not yet been tested on the Android version of the app, it is likely that it does not work.
I will update this issue when we have improved the Android version.

**Comment by LFGaming** [comment]
okay, no problem. then ill wait a bit longer, shall I close the issue then?

**Comment by aeddi** [comment]
You can leave it open so that we can update it when a fix is merged. 👍

**Comment by x80486** [comment]
It's been a while since this was updated. I'm still unable to backup the account in the latest (2.431.2) version.

When do you think this would be released?

**Comment by jefft0** [comment]
We intend to support the reliability of backups. We'll keep this in backlog as a tracking issue.

**Comment by D4ryl00** [comment]
Do you know if this bug is impacting the iOS version?

**Comment by D4ryl00** [comment]
Ok thanks, no need to give me the file I think.
